import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Studio Runtime App",
  description: "Generated by Local Agent Studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          fontFamily:
            'system-ui, -apple-system, "Segoe UI", "Helvetica Neue", sans-serif',
          background: "#f8fafc",
          color: "#0f172a",
          minHeight: "100vh",
        }}
      >
        {children}
      </body>
    </html>
  );
}
