from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from orchestrator.agents.design_critique import DesignCritiqueAgent, evaluate_design
from orchestrator.agents.ui_product_team import UiProductTeamAgent
from orchestrator.agents.ui_designer import UiDesignerAgent
from orchestrator.bootstrap import initialize_workspace
from orchestrator.config import resolve_paths
from orchestrator.core.run_manager import create_engine
from orchestrator.db import Database


class DesignAgentTests(unittest.TestCase):
    def test_ui_designer_generates_portfolio_design_and_critique_passes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            paths = resolve_paths(tmp)
            initialize_workspace(paths)
            engine = create_engine(paths)
            project = engine.create_project("Build a personal portfolio builder web app", paths.projects_dir)
            run = engine.run(project["id"], "software_project")

            design = UiDesignerAgent(Database(paths.db_path)).generate_design(project=project, run_id=run["run_id"])
            critique = DesignCritiqueAgent(Database(paths.db_path)).run(project=project, run_id=run["run_id"])

            self.assertTrue(design.user_flow_path.exists())
            self.assertTrue(design.design_system_path.exists())
            self.assertTrue(design.component_spec_path.exists())
            self.assertEqual(critique.evaluation.status, "pass", critique.evaluation.hard_failures)
            self.assertGreaterEqual(critique.evaluation.final_score, 64)
            self.assertIn("Design Critique", critique.critique_md_path.read_text(encoding="utf-8"))

    def test_design_critique_fails_workflow_stubs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            design_dir = root / "docs/design"
            design_dir.mkdir(parents=True)
            for name in ["user-flow.md", "design-system.md", "component-spec.md"]:
                (design_dir / name).write_text(
                    "# Design Notes\n\nStatus: generated by the local deterministic MVP stub.\n",
                    encoding="utf-8",
                )

            evaluation = evaluate_design(root)

            self.assertEqual(evaluation.status, "fail")
            self.assertTrue(any("stubs" in failure.lower() for failure in evaluation.hard_failures))

    def test_ui_product_team_generates_full_portfolio_team_package(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            paths = resolve_paths(tmp)
            initialize_workspace(paths)
            engine = create_engine(paths)
            project = engine.create_project("Build a personal portfolio builder web app", paths.projects_dir)
            run = engine.run(project["id"], "software_project")
            project_path = Path(project["path"])
            product_dir = project_path / "docs/product"
            product_dir.mkdir(parents=True, exist_ok=True)
            (product_dir / "post-build-product-review.json").write_text(
                json.dumps(
                    {
                        "domain_type": "portfolio",
                        "status": "needs_revision",
                        "blockers": [
                            "The builder does not coach the user through what makes a portfolio persuasive.",
                            "Research does not visibly shape the generated product experience.",
                            "No browser automation or screenshot evidence exists for the generated UI.",
                        ],
                    }
                ),
                encoding="utf-8",
            )

            result = UiProductTeamAgent(Database(paths.db_path)).run(project=project, run_id=run["run_id"])
            contracts = json.loads(result.contracts_json_path.read_text(encoding="utf-8"))
            score = json.loads(result.score_json_path.read_text(encoding="utf-8"))

            self.assertTrue(result.ux_flow_lead_path.exists())
            self.assertTrue(result.visual_design_lead_path.exists())
            self.assertTrue(result.asset_strategy_lead_path.exists())
            self.assertTrue(result.visual_qa_lead_path.exists())
            self.assertTrue(result.design_critic_path.exists())
            self.assertTrue(result.reference_traceability_path.exists())
            self.assertTrue(result.screen_spec_path.exists())
            self.assertTrue(result.template_spec_path.exists())
            self.assertTrue(result.dev_handoff_path.exists())
            self.assertTrue(result.design_contract_json_path.exists())
            self.assertEqual(contracts["gate"], "ui_team_handoff")
            self.assertEqual(score["status"], "ready_for_dev_team_evidence_pending")
            self.assertIn("visual_qa_evidence", score["dimensions"])
            self.assertIn("Case Study", result.dev_handoff_path.read_text(encoding="utf-8"))
            design_contract = json.loads(result.design_contract_json_path.read_text(encoding="utf-8"))
            self.assertEqual(design_contract["gate"], "ui_team_design_contract")
            self.assertGreaterEqual(len(design_contract["templates"]), 4)


if __name__ == "__main__":
    unittest.main()
